spring:
  application:
    name: shardingsphere-jdbc-demo


  shardingsphere:
#    enabled: true
    props:
      sql-show: false

#    单机模式
    mode:
      type: Standalone
      repository:
        type: JDBC
#    数据源配置
    datasource:
      names: testdb
      testdb:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.3:3306/testdb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
        username: test
        password: pw0826

#    分片规则配置
    rules:
      sharding:
        tables:
          test_user:
            actual-data-nodes: testdb.test_user_${0..9}
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: test_user_inline
        sharding-algorithms:
          test_user_inline:
            type: INLINE
            props:
              algorithm-expression:  test_user_${id.intdiv(1000000)}
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
